import Head from 'next/head'
import Image from 'next/image'
import dividerdsk from '../utils/pattern-divider-desktop.svg'
import dice from '../utils/icon-dice.svg'
import { useEffect, useState } from 'react'
import axios from 'axios'

export default function Home() {

  const [advice, setAdvice] = useState('');
  const [adviceID, setAdviceID] = useState(0);

  const getAdvice = async () => {
    await axios.get('https://api.adviceslip.com/advice')
      .then((res) => {
        setAdvice(res.data.slip.advice);
        setAdviceID(res.data.slip.id);
      })
      .catch((err) => {
        console.log(err);
      })
  };

  useEffect(() => {
    getAdvice();
  }, []);
    
  

  return (
    <div className='dgblue w-[22rem] md:w-[30rem] rounded-lg'>
      <Head>
        <title>Advice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col gap-8 justify-between items-center'>
        <h2 className='text-lime-400 mt-8 text-sm'>ADVICE #{adviceID}</h2>
        <h1 className='text-white text-2xl font-semibold text-center mx-4'>&quot;{advice}&quot;</h1>
        <div className='back'></div>
        <button onClick={getAdvice} className='rounded-full translate-y-4 bg-lime-400 w-10 h-10 flex items-center justify-center hover:shadow-[0px_0px_50px_14px_lime]'>
          <Image src={dice} alt="dice" width={15} height={15}></Image>
        </button>
      </div>
    </div>
  )
}
